### ISSUE TITLE
pkg-config free detection of installed MKL

### ISSUE THREAD

**Issue by termoshtt** [rust-math/intel-mkl-src#37]
As https://github.com/rust-math/intel-mkl-src/pull/36#issuecomment-643576170, pkg-config setting of official apt/yum repository is broken.

TODO
---------
- [ ] Create test container for apt/yum installation like #36 
- [ ] Seek mkl using environment variable e.g. `MKLROOT` which specify where the MKL is installed

**Comment by termoshtt** [comment]
Related to `never-download` option discussed in #29

**Comment by Andlon** [comment]
Just leaving this here as it might interest you. You might want to take a look at our (unpublished) crate [mkl-sys](https://github.com/Andlon/mkl-sys), for which we also had to use something else than `pkgconfig` after Intel completely broke their `pkgconfig` configurations in MLK 2020, as well as to better support Windows. Note that the scope of our crate is a little bit different than `intel-mkl-src`: it exposes the *entire* MKL, not just BLAS. We predominantly needed sparse linear algebra, not the BLAS API, which led us to building this crate (along with the fact that it relies on the installed MKL installation rather than attempting to download something).
